# Generated by Django 4.1.1 on 2022-10-08 19:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('category_slug', models.CharField(max_length=100, verbose_name='Category Slug')),
                ('site_added_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Added By')),
                ('last_updated_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Last Updated By')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Parameter Name')),
                ('parameter_slug', models.CharField(max_length=100, verbose_name='Parameter Slug')),
                ('site_added_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Added By')),
                ('last_updated_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Last Updated By')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Station')),
                ('site_id', models.CharField(default=None, max_length=80, null=True, verbose_name='StationID/SiteID')),
                ('key', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Key or Token')),
                ('prefix', models.CharField(max_length=64, unique=True, verbose_name='site Prefix')),
                ('version', models.CharField(blank=True, default='ver_1.0', max_length=10, verbose_name='Software Version')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('zipcode', models.IntegerField(blank=True, default=None, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('state', models.CharField(max_length=80, null=True)),
                ('city', models.CharField(max_length=80, null=True)),
                ('district', models.CharField(max_length=80, null=True)),
                ('country', models.CharField(blank=True, default='India', editable=False, max_length=80)),
                ('user_email', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Customer Alert Email')),
                ('user_phone', models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Customer Alert Contact')),
                ('to_sdc', models.BooleanField(blank=True, default=False, help_text='send data to SDC', verbose_name='To SDC')),
                ('to_nic', models.BooleanField(blank=True, default=False, help_text='send data to NIC', verbose_name='To NIC')),
                ('to_ce_okhla', models.BooleanField(blank=True, default=False, help_text='send data to CE Okhla', verbose_name='To CE Okhla')),
                ('to_wims', models.BooleanField(blank=True, default=False, help_text='send data to WIMS', verbose_name='To WIMS')),
                ('enable_led', models.BooleanField(default=False, verbose_name='Led Display')),
                ('hours2delay', models.IntegerField(default=4, verbose_name='set Delay in N mins')),
                ('hours2offline', models.IntegerField(default=48, verbose_name='set Offline in N mins')),
                ('enable_email_alerts', models.BooleanField(blank=True, default=False, help_text='send email alerts', verbose_name='Email Alerts')),
                ('enable_sms_alerts', models.BooleanField(blank=True, default=False, help_text='send sms alerts', verbose_name='SMS Alerts')),
                ('max_email_alerts', models.CharField(max_length=100, null=True)),
                ('max_sms_alerts', models.CharField(max_length=100, null=True)),
                ('calibration', models.BooleanField(default=False, help_text='calibration enabled')),
                ('site_added_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Added By')),
                ('last_updated_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Last Updated By')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
