# Generated by Django 4.1.1 on 2022-09-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='site',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='site',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_added_by',
        ),
    ]
