# Generated by Django 4.1.1 on 2022-09-26 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0002_remove_site_created_at_remove_site_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='site',
            name='last_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='site',
            name='last_updated_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_added_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Added By'),
        ),
    ]
