# Generated by Django 4.1.1 on 2022-11-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0003_site_site_category_alter_site_site_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ce_okhla_alert_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='CE Okhla Alert Email'),
        ),
        migrations.AddField(
            model_name='site',
            name='nic_alert_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='NIC Alert Email'),
        ),
        migrations.AddField(
            model_name='site',
            name='sdc_alert_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='SDC Alert Email'),
        ),
    ]
