# Generated by Django 4.1.1 on 2022-11-16 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0004_site_ce_okhla_alert_email_site_nic_alert_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='monitoring_app.site')),
                ('last_seen', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Seen')),
                ('last_upload_info', models.TextField(blank=True, default='', max_length=256)),
                ('readings', models.TextField(blank=True, max_length=999)),
                ('file_info', models.TextField(default=None, null=True)),
                ('cpcb_status', models.BooleanField(default=False, verbose_name='CPCB Upload Status')),
                ('pcb_status', models.BooleanField(default=False, verbose_name='PCB Upload Status')),
                ('received_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('freq', models.CharField(blank=True, max_length=256, verbose_name='File Frequency')),
                ('var5', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Reading2022',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('readings', models.TextField(blank=True, max_length=999)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings2022', to='monitoring_app.site')),
            ],
            options={
                'unique_together': {('site', 'timestamp')},
            },
        ),
    ]
