# Generated by Django 4.1.1 on 2022-12-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0006_site_site_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='site_status',
            field=models.CharField(default='NAT', max_length=20, verbose_name='site status'),
        ),
    ]
