# Generated by Django 4.1.1 on 2022-12-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0007_siteinfo_site_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen'),
        ),
    ]
