# Generated by Django 4.1.1 on 2022-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0008_alter_siteinfo_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='readings',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
