# Generated by Django 4.1.1 on 2022-12-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0011_alter_siteinfo_file_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
