# Generated by Django 4.1.1 on 2022-12-14 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0012_alter_siteinfo_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
