# Generated by Django 4.1.1 on 2022-12-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0013_siteinfo_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='cpcb_status',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='pcb_status',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='nic_status',
            field=models.BooleanField(default=False, verbose_name='NIC Upload Status'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='sdc_status',
            field=models.BooleanField(default=False, verbose_name='SDC Upload Status'),
        ),
    ]
