# Generated by Django 4.1.1 on 2022-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0014_remove_siteinfo_cpcb_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading2022',
            name='readingsDict',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
