# Generated by Django 4.1.1 on 2022-12-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0015_reading2022_readingsdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading2022',
            name='readingsDict',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='readingsDict',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
