# Generated by Django 4.1.1 on 2022-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0017_parameter_parameter_max_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_parameter',
            field=models.ManyToManyField(blank=True, null=True, to='monitoring_app.parameter', verbose_name='Site Parameters'),
        ),
    ]
