# Generated by Django 4.1.1 on 2022-12-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0018_site_site_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site_parameter',
        ),
        migrations.AddField(
            model_name='parameter',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.site', verbose_name='Site'),
        ),
    ]
