# Generated by Django 4.1.1 on 2022-10-08 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('phone', models.CharField(max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('last_pwd_updated', models.DateField(auto_now=True, verbose_name='Password Updated On')),
                ('user_type', models.CharField(choices=[('1', 'Active User'), ('2', 'Staff User'), ('3', 'Super Admin')], max_length=20)),
                ('demo_user', models.BooleanField(default=False)),
                ('address', models.TextField(default=None, null=True)),
                ('zipcode', models.IntegerField(default=None, null=True)),
                ('state', models.CharField(max_length=80, null=True)),
                ('city', models.CharField(max_length=80, null=True)),
                ('country', models.CharField(default='India', editable=False, max_length=80)),
                ('added_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Added By')),
                ('last_updated_by', models.CharField(blank=True, default='', max_length=120, verbose_name='Last Updated By')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('permissions', models.ManyToManyField(default=None, to='auth.permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
