# Generated by Django 4.1.1 on 2022-09-26 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='added_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_updated_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Last Updated By'),
        ),
    ]
